/**
 * Central icon registry for the app.
 *
 * Replace icons here one by one with your own SVG/components and the rest of
 * the project will update automatically without touching feature files again.
 *
 * Example:
 * export function BookOpen(props: AppIconProps) {
 *   return (
 *     <svg viewBox="0 0 24 24" fill="none" {...props}>
 *       ...
 *     </svg>
 *   );
 * }
 */

export type {
  LucideIcon,
  LucideIcon as AppIcon,
  LucideProps,
  LucideProps as AppIconProps,
} from "lucide-react";

export {
  AlertCircle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BarChart3,
  Bell,
  BookMarked,
  BookmarkPlus,
  BookOpen,
  CalendarDays,
  Camera,
  Check,
  CheckCircle2,
  CheckIcon,
  ChevronDown,
  ChevronDownIcon,
  ChevronLeft,
  ChevronLeftIcon,
  ChevronRight,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlert,
  CircleCheckBig,
  CircleDot,
  CircleIcon,
  ClipboardList,
  Clock3,
  Download,
  Eye,
  FileJson,
  FilePenLine,
  FilePlus2,
  FileText,
  Flame,
  FolderArchive,
  Globe2,
  GripVerticalIcon,
  Hash,
  Home,
  Inbox,
  Info,
  Layers3,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailOpen,
  MailX,
  MapPin,
  Medal,
  Menu,
  MinusIcon,
  MoreHorizontal,
  MoreHorizontalIcon,
  MoreVertical,
  Palette,
  PanelLeftClose,
  PanelLeftIcon,
  PanelLeftOpen,
  PencilLine,
  Play,
  PlayCircle,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  ScanSearch,
  Search,
  SearchCheck,
  SearchIcon,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserPlus,
  UserRound,
  Users,
  Wand2,
  X,
  XCircle,
  XIcon,
} from "lucide-react";
